#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: fluent-bit
  namespace: dev-cluster-addons-install
  annotations:
    kapp.k14s.io/change-group: fluent-bit
    #! We want to make sure we don't delete the service account used by this 
    #! package install before we delete the PackageInstall object itself, 
    #! otherwise the deletion will hang.  Check out the "package-basics" 
    #! directory for the service account creation
    kapp.k14s.io/change-rule.serviceaccount: delete before deleting serviceaccount
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: add-configmap-versioning
spec:
  serviceAccountName: dev-cluster-addons-sa
  packageRef:
    refName: fluent-bit.tanzu.vmware.com
    versionSelection:
      constraints: ">=1.8.0 <1.9.0"
      prereleases: {}
  values:
  - secretRef:
      name: fluentbit-values
---
apiVersion: v1
kind: Secret
metadata:
  name: fluentbit-values
  namespace: dev-cluster-addons-install
stringData:
  #@yaml/text-templated-strings
  data-values: |
    fluent_bit:
      config:
        filters: |
          [FILTER]
            Name                kubernetes
            Match               kube.*
            Kube_URL            https://kubernetes.default.svc:443
            Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
            Kube_Tag_Prefix     kube.var.log.containers.
            Merge_Log           On
            Merge_Log_Key       log_processed
            K8S-Logging.Parser  On
            K8S-Logging.Exclude On

          [FILTER]
            Name                modify
            Match               *
            Rename message text
            Add cluster (@= data.values.cluster_name @)
---
apiVersion: v1
kind: Secret
metadata:
  name: add-configmap-versioning
  namespace: dev-cluster-addons-install
stringData:
  overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata":{"name": "fluent-bit-config"}}), expects=1
    ---
    metadata:
      #@overlay/match-child-defaults missing_ok=True
      annotations:
        kapp.k14s.io/versioned: ""