apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-cluster-addons-sa-role
  namespace: dev-cluster-addons-install
  annotations: 
    kapp.k14s.io/change-group: serviceaccount
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-cluster-addons-sa-rolebinding
  namespace: dev-cluster-addons-install
  annotations: 
    kapp.k14s.io/change-group: serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev-cluster-addons-sa-role
subjects:
- kind: ServiceAccount
  name: dev-cluster-addons-sa
  namespace: dev-cluster-addons
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-cluster-addons-sa
  namespace: dev-cluster-addons-install
  annotations: 
    kapp.k14s.io/change-group: serviceaccount
