---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: dev-cluster-addons-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster with dev-cluster-addons installed
          restartPolicy: OnFailure